force-app/main/default/objects/Account_Contract__c/Account_Contract__c.object-meta.xml
<CustomObject>
    <label>Account Contract</label>
    <nameField>
        <displayFormat>Contract - {0000}</displayFormat>
        <label>Account Contract Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_Contract__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Contracts</relationshipLabel>
    <relationshipName>Account_Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account_Contract_Clause__c/Account_Contract_Clause__c.object-meta.xml
<CustomObject>
    <label>Account Contract Clause</label>
    <nameField>
        <displayFormat>Clause - {0000}</displayFormat>
        <label>Account Contract Clause Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Contract Clauses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_Contract_Clause__c/fields/Account_Contract__c.field-meta.xml
<CustomField>
    <fullName>Account_Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Contract</label>
    <referenceTo>Account_Contract__c</referenceTo>
    <relationshipLabel>Account Contract Clauses</relationshipLabel>
    <relationshipName>Account_Contract_Clauses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account_Contract_Clause__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>India</fullName>
            </value>
            <value>
                <fullName>US</fullName>
            </value>
            <value>
                <fullName>Netherlands</fullName>
            </value>
            <value>
                <fullName>Germany</fullName>
            </value>
            <value>
                <fullName>Belgium</fullName>
            </value>
            <value>
                <fullName>Spain</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AccountContractController.cls
public with sharing class AccountContractController {
    @AuraEnabled(cacheable=true)
    public static List<Account_Contract_Clause__c> getAccountContractClauses(String accountId, String billingCountry) {
        // Query Account Contract Clause records based on Account Id of Account Contract and Billing Country
        return [SELECT id, Name,Country__c FROM Account_Contract_Clause__c WHERE 
                Account_Contract__r.Account__c = :accountId AND Country__c = :billingCountry order by Name];
    }

    @AuraEnabled
    public static Id createAccountContract(String accountId, List<Account_Contract_Clause__c> contractClauses) {
        Account_Contract__c newContract = new Account_Contract__c();
       try{
       // Create a new Account Contract
        newContract.Account__c = accountId; // Link the new contract to the Account
        Database.insert(newContract,false);

        // Save contractClauses as a file linked to the new Account Contract record
        String clausesText = String.join(contractClauses, '\n');
        Blob clausesBlob = Blob.valueOf(clausesText);
        
        ContentVersion content = new ContentVersion();
        content.Title = 'AccountContractClauses.txt';
        content.PathOnClient = 'AccountContractClauses.txt';
        content.VersionData = clausesBlob;
        content.FirstPublishLocationId = newContract.Id;
        Database.insert(content,false);
        }
        catch(Exception ex){
            System.debug('Exception occured :'+ex.getMessage());
        }
        
        return newContract.Id <> null ? newContract.Id : null;
    }
}