force-app/main/default/objects/Account_Contract__c/Account_Contract__c.object-meta.xml
<CustomObject>
    <label>Account Contract</label>
    <nameField>
        <displayFormat>Contract - {0000}</displayFormat>
        <label>Account Contract Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_Contract__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Contracts</relationshipLabel>
    <relationshipName>Account_Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account_Contract_Clause__c/Account_Contract_Clause__c.object-meta.xml
<CustomObject>
    <label>Account Contract Clause</label>
    <nameField>
        <displayFormat>Clause - {0000}</displayFormat>
        <label>Account Contract Clause Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Contract Clauses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_Contract_Clause__c/fields/Account_Contract__c.field-meta.xml
<CustomField>
    <fullName>Account_Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Contract</label>
    <referenceTo>Account_Contract__c</referenceTo>
    <relationshipLabel>Account Contract Clauses</relationshipLabel>
    <relationshipName>Account_Contract_Clauses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account_Contract_Clause__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>India</fullName>
            </value>
            <value>
                <fullName>US</fullName>
            </value>
            <value>
                <fullName>Netherlands</fullName>
            </value>
            <value>
                <fullName>Germany</fullName>
            </value>
            <value>
                <fullName>Belgium</fullName>
            </value>
            <value>
                <fullName>Spain</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AccountContractControllerTest.cls
@isTest
public class AccountContractControllerTest {

    @isTest
    static void testGetAccountContractClauses() {
        // Create test Account and Account Contract records
        Account testAccount = new Account(Name = 'Test Account', BillingCountry = 'US');
        insert testAccount;
        
        Account_Contract__c testContract = new Account_Contract__c(Account__c = testAccount.Id);
        insert testContract;
        
        // Create test Account Contract Clauses
        List<Account_Contract_Clause__c> testClauses = new List<Account_Contract_Clause__c>{
            new Account_Contract_Clause__c(Country__c = 'India', Account_Contract__c = testContract.Id),
            new Account_Contract_Clause__c(Country__c = 'Netherlands', Account_Contract__c = testContract.Id),
            new Account_Contract_Clause__c(Country__c = 'Germany', Account_Contract__c = testContract.Id)
        };
        insert testClauses;

        // Call the controller method
        List<Account_Contract_Clause__c> resultClauses = AccountContractController.getAccountContractClauses(testAccount.Id, 'US');
        
    }

    @isTest
    static void testCreateAccountContract() {
        // Create test Account
        Account testAccount = new Account(Name = 'Test Account', BillingCountry = 'US');
        insert testAccount;

        // Call the controller method to create an Account Contract
        Account_Contract__c createdContract = new Account_Contract__c(Account__c = testAccount.Id);
        Test.startTest();
        Id newContractId = AccountContractController.createAccountContract(testAccount.Id, new List<Account_Contract_Clause__c>());
        Test.stopTest();
    }
    
    @isTest
    static void testException(){
        try{
            AccountContractController.createAccountContract(null,null);
        }
        catch(Exception ex){}
    }
}